default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: smartcards_development

test:
  <<: *default
  database: smartcards_test

production:
  <<: *default
  database: smartcards